curl -X POST http://192.168.1.148:23000/api/user/login \
-H "Content-Type: application/json" \
-d '{
"user_id": "myuser", 
"user_password": "mypassword"
}'
###

POST http://192.168.1.148:23000/api/user/login \

###


GET http://192.168.1.148:25000/api/test/test1 \
###


GET http://192.168.1.148:25000/api/test/test1

###

curl -X POST http://192.168.1.148:25000/api/test/test2 \
-H "Content-Type: application/json" \
-d '{
"test_body1": "test"
}'

###
GET http://192.168.1.148:25000/api/test/test3
###

curl -X POST http://192.168.1.148:25000/api/user/login \
  -H 'Content-Type: application/json' \
  -d '{"username": "myuser", "password": "mypassword", "rememberMe": true}'

###

curl -X DELETE http://192.168.1.148:25000/api/post/post_delete \
-H "Content-Type: application/json" \
-d '{"post_id": "20241012034110785680"}'
###

curl -X post http://192.168.1.148:25000/api/post/post_read \
-H "Content-Type: application/json" \
-d '{"post_id": "20241011140544727674"}'
###
curl -X POST \
     -H "Content-Type: multipart/form-data; boundary=boundary" \
     -F "image=@./test.png" \
     http://192.168.1.148:25000/api/drive/file_create
###

