# Use an official Node.js image
FROM node:22-alpine

# 必要なビルドツールとPythonをインストール
RUN apk add --no-cache python3 make g++ pkgconfig pixman-dev cairo-dev pango-dev jpeg-dev giflib-dev git

# 作業ディレクトリを作成
WORKDIR /usr/src/backend

# 依存関係をインストールするためにpackage.jsonとpackage-lock.jsonをコピー
COPY ./backend/package**.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションコードをコピー
COPY . .

# Expose the internal port
EXPOSE 5000

# アプリを開発モードで起動
CMD ["npm", "start"]


